name: test
on:
  push:
    branches:
      - main

env:
  BROWSER_NAME: ${{ secrets.BROWSER_NAME }}
  BASE_WEB_URL: ${{ secrets.BASE_WEB_URL }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci --no-fund
          npx cypress cache path
          npx cypress cache list
          npm run cy-verify
          npm run cy-info
          npm run create-env-github && cat .env ; echo
          mkdir -p mochawesome-report && npm run

      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v3
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('package-lock.json') }}

      - name: Run tests
        run: npm run cy-login